### ISSUE TITLE
Add a single email to multiple lists

### ISSUE THREAD

**Issue by josephrussell** [sendgrid/sendgrid-subscription-widget#10]
I'm looking to give the user the option to subscribe to 1 or more lists at once. For example, different lists for based on city or frequency.

It would be handy to use this subscription widget but it appears each subscription widget is attached to a single list only. 

I'm trying to determine if I should attempt make this work with this widget or move to using the Marketing Email api directly and make a request per list per email.
https://sendgrid.com/docs/API_Reference/Marketing_Emails_API/emails.html

Any advice would be appreciated.

**Comment by josephrussell** [comment]
Moved away from sendgrid to another provider.

**Comment by mezza** [comment]
Out of curiosity, who?
